; Credits: @kebisfr
; {"Name":"Bamboo","Pattern":"keb-bamb","DriftCheck":0,"PatternInvertFB":0,"PatternInvertLR":0,"PatternReps":3,"PatternShift":0,"PatternSize":"M","ReturnType":"Walk","RotateDirection":"Left","RotateTimes":2,"SprinklerDist":4,"SprinklerLoc":"Upper Left","UntilMins":60,"UntilPack":95}
loop reps {
   nm_Walk(7, FwdKey) 
   nm_Walk(13, RightKey)
   nm_Walk(6, LeftKey)
   nm_Walk(13, BackKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, FwdKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, FwdKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, FwdKey)
   nm_Walk(1, RightKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, RightKey)
   nm_Walk(9, FwdKey)
   nm_Walk(2, RightKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, RightKey)
   nm_Walk(9, FwdKey)
   nm_Walk(3, RightKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, FwdKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, FwdKey)
   nm_walk(2, LeftKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, LeftKey)
   nm_Walk(9, FwdKey)
   nm_Walk(1, RightKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, RightKey)
   nm_Walk(9, FwdKey)
   nm_Walk(2, RightKey)
   nm_Walk(9, BackKey)
   nm_Walk(2, RightKey)
   nm_Walk(9, FwdKey)
}